name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push API image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/api:latest -f ./api/Dockerfile ./api
        docker push ${{ secrets.DOCKER_USERNAME }}/api:latest

    - name: Build and push Web image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/web:latest -f ./web/Dockerfile ./web
        docker push ${{ secrets.DOCKER_USERNAME }}/web:latest

  deploy:
    name: Deploy to Linode
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /path/to/your/project
          docker-compose pull
          docker-compose up -d --scale web=2 --scale api=3
