name: Build, Push Docker Images, and Update Linode Server

on:
  push:
    branches:
      - '**'  # Trigger the workflow on pushes to any branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 4: Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Verify the installation

      # Step 5: Build and push images using Docker Compose
      - name: Build and push Docker Compose services
        run: |
          docker-compose -f docker-compose.yml build  # Build the services
          docker-compose -f docker-compose.yml push   # Push the images

  update-linode:
    name: Update Linode Server
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      # Step 1: Execute remote SSH commands using password
      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            # Navigate to the deployment directory
            cd /home/username/github-actions-compose

            # Pull the latest images
            docker-compose pull

            # Restart the services with the updated images
            docker-compose up -d  # '-d' for detached mode

            # Run additional commands as needed, for example:
            # docker-compose restart
