name: Build, Push Docker Compose Services, and Update Linode Server

on:
  push:
    branches:
      - '**'  # Trigger the workflow on pushes to any branch

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and Push the Web Service
      - name: Build and push web image
        run: |
          docker compose build web
          docker compose push web

  build-api:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and Push the API Service
      - name: Build and push API image
        run: |
          docker compose build api
          docker compose push api

  update-linode:
    name: Update Linode Server
    needs:
      - build-web
      - build-api
    runs-on: ubuntu-latest
    steps:
      # Step 1: Execute remote SSH commands to update the server
      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            # Navigate to the deployment directory and restart services
            cd /path/to/your/deployment
            docker compose pull
            docker compose up -d --remove-orphans
