name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger this on push to the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Login to DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and push Docker images using Docker Compose
    - name: Build and push Docker images
      run: |
        docker-compose -f docker-compose.yml build
        docker-compose -f docker-compose.yml push

    # SSH into Linode server and pull the latest images, stop old containers, and restart with the latest images
    - name: Deploy to Linode
      uses: appleboy/ssh-action@v0.1.0
      with:
        host: ${{ secrets.LINODE_HOST }}
        username: ${{ secrets.LINODE_USER }}
        key: ${{ secrets.LINODE_SSH_KEY }}
        script: |
          # Navigate to the directory containing docker-compose.yml on the server
          cd /path/to/your/docker-compose/directory  # Replace with the actual directory

          # Pull the latest images from DockerHub
          docker-compose -f docker-compose.yml pull

          # Stop and remove existing containers (if any)
          docker-compose -f docker-compose.yml down || true

          # Restart the containers with the latest images
          docker-compose -f docker-compose.yml up -d
